### PR TITLE
Ui bug fixing

### LINKED ISSUE #24: Clickable "Failed Controls" button in Compliance View
Currently, the "Failed Controls" button in the Compliance View is not clickable.

### LINKED ISSUE #35: Link in Compliance view to rule incorrect
The link is still „analysis“ instead of „rules“

### PR DESCRIPTION
**Pull request by immqu**
Closes #24
Closes #35

### CODE REVIEW

**Comment by oxisto** [comment]
It would be nice that if you click on failed controls it would automatically change the filter in the compliance view to only failed controls. This should be doable with a query parameter similar to how it is solved in the rules component. Can you look into this?

**Comment by immqu** [comment]
I have added the query params; however, the filterOptions persist when leaving the view, shall we reset it when visiting the certification normally?

**Comment by oxisto** [comment]
Maybe we should get rid of the persistence all together and do it like this:
- Click on „failed controls“ -> failed only
- Click on „passed controls“ -> passed only
- Click on title -> all

**Comment by oxisto** [comment]
Made a change to keep the old style buttons for now since we may want to globally replace them at some point. Otherwise ready to merge once tests are ok.

**Pull request merged**
