### PR TITLE
Add property interval to metric

### PR DESCRIPTION
**Pull request by anatheka**

### CODE REVIEW

**Comment by oxisto** [comment]
This is slightly blocked by https://github.com/google/gnostic/issues/351

**Comment by anatheka** [comment]
Should we then also block this PR until that is resolved?

**Comment by anatheka** [comment]
> This is slightly blocked by [google/gnostic#351](https://github.com/google/gnostic/issues/351)

**Comment by anatheka** [comment]
Change Duration to int with seconds.

**Review by oxisto — APPROVED** [review]

**Pull request merged**
